export const selectedProjects = [
  {
    name: 'Permission Bureau',
    slug: 'auspice',
    domain: 'Identity and permission intelligence',
    summary: 'A policy-focused system for modeling permissions, approvals, and traceable access decisions.',
    problem: 'Permission workflows need explicit policy boundaries and reviewable decision history.',
    systemDesign: 'Policy evaluation, approval records, and audit-oriented system boundaries organized for repeatable review.',
    evidence: 'Repository signal: a substantial Python codebase centered on permission and policy workflows.',
    stack: ['Python'],
    repository: 'https://github.com/devpilotX/auspice',
    live: null
  },
  {
    name: 'Veydria',
    slug: 'veydria',
    domain: 'Automation orchestration',
    summary: 'An orchestration system focused on controlled automation and explicit execution state.',
    problem: 'Operational automation becomes difficult to trust when jobs, policies, and operator controls are implicit.',
    systemDesign: 'Typed orchestration flows with visible state transitions and controlled operator intervention.',
    evidence: 'Repository signal: a substantial TypeScript implementation with application and systems layers.',
    stack: ['TypeScript'],
    repository: 'https://github.com/devpilotX/Veydria',
    live: null
  },
  {
    name: 'Quant',
    slug: 'quant',
    domain: 'Systematic research infrastructure',
    summary: 'A Python research system for strategy analysis, simulation, and reproducible execution workflows.',
    problem: 'Quantitative research needs repeatable inputs, testable strategy logic, and clear separation from live execution.',
    systemDesign: 'Research, simulation, and execution concerns organized around reproducibility and controlled validation.',
    evidence: 'Repository signal: a large Python project with dedicated quantitative research and validation workflows.',
    stack: ['Python'],
    repository: 'https://github.com/devpilotX/Quant',
    live: null
  },
  {
    name: 'ProofSmith',
    slug: 'proofsmith',
    domain: 'Formal verification tooling',
    summary: 'A Lean project exploring machine-checkable reasoning and proof-oriented development.',
    problem: 'Important technical claims need stronger evidence than prose and manual review alone.',
    systemDesign: 'Formal definitions and proofs expressed in Lean for deterministic, machine-checkable verification.',
    evidence: 'Repository signal: a focused Lean codebase built around formal proof artifacts.',
    stack: ['Lean'],
    repository: 'https://github.com/devpilotX/ProofSmith',
    live: null
  },
  {
    name: 'FerroDB',
    slug: 'ferrodb',
    domain: 'Data infrastructure',
    summary: 'A compact Rust data-system project emphasizing explicit storage behavior and typed boundaries.',
    problem: 'Storage components need predictable behavior, constrained interfaces, and low operational ambiguity.',
    systemDesign: 'Rust modules organized around type safety, storage operations, and deterministic system behavior.',
    evidence: 'Repository signal: a focused Rust implementation released under the MIT License.',
    stack: ['Rust'],
    repository: 'https://github.com/devpilotX/FerroDB',
    live: null
  },
  {
    name: 'AEGIS',
    slug: 'aegis',
    domain: 'Security assurance',
    summary: 'A TypeScript security platform organized around control checks, findings, and remediation workflows.',
    problem: 'Security programs need actionable evidence and prioritization rather than static checklists.',
    systemDesign: 'Control-oriented workflows, structured findings, and remediation tracking in a typed application stack.',
    evidence: 'Repository signal: a TypeScript security project with an Apache 2.0 license and active issue tracking.',
    stack: ['TypeScript'],
    repository: 'https://github.com/devpilotX/aegis',
    live: null
  },
  {
    name: 'Paisa Reality',
    slug: 'paisarealitymoney',
    domain: 'Personal finance clarity',
    summary: 'A public financial education product that explains salary, pricing, inflation, and purchasing power.',
    problem: 'Financial numbers are difficult to interpret without context, comparison, and transparent assumptions.',
    systemDesign: 'A TypeScript product that turns financial inputs into understandable scenarios and reference comparisons.',
    evidence: 'Repository signal: a substantial TypeScript application with a public product destination.',
    stack: ['TypeScript'],
    repository: 'https://github.com/devpilotX/paisarealitymoney',
    live: 'https://paisareality.com'
  },
  {
    name: 'Bank Legacy',
    slug: 'bank-legacy',
    domain: 'Banking modernization',
    summary: 'A Java project exploring controlled modernization around legacy banking workflows.',
    problem: 'Legacy financial systems must evolve without weakening transaction integrity or migration controls.',
    systemDesign: 'Java services and migration-oriented boundaries designed around incremental modernization.',
    evidence: 'Repository signal: a public Java project focused on banking system design.',
    stack: ['Java'],
    repository: 'https://github.com/devpilotX/Bank-Legacy',
    live: null
  },
  {
    name: 'Notion Agent',
    slug: 'notion-agent',
    domain: 'Self-hosted agent infrastructure',
    summary: 'A local-first agent workbench with model routing, retrieval, MCP connections, triggers, and streaming execution.',
    problem: 'Agent systems need inspectable execution, protected credentials, grounded context, and deployable operational boundaries.',
    systemDesign: 'Next.js frontend and NestJS engine connected over HTTP and Server-Sent Events, backed by PostgreSQL with optional pgvector and Redis.',
    evidence: 'Repository signal: CI, MIT license, encrypted provider keys, account mode, retrieval, MCP tooling, triggers, and an extensive documented API.',
    stack: ['Next.js', 'NestJS', 'PostgreSQL', 'TypeScript'],
    repository: 'https://github.com/devpilotX/Notion-Agent',
    live: null
  },
  {
    name: 'Value.Codes',
    slug: 'value-codes',
    domain: 'Developer tools',
    summary: 'A browser-first developer utility and community platform with tools, compiler access, content, profiles, and moderation.',
    problem: 'Common engineering tasks are slowed by fragmented utilities, sign-up walls, and unclear data handling.',
    systemDesign: 'Server-rendered Express and EJS application with MySQL, session storage, CSRF controls, nonce-based CSP, validation, and structured logging.',
    evidence: 'Repository signal: documented security controls, database schema, migrations, operational health checks, and a live public destination.',
    stack: ['Node.js', 'Express', 'MySQL', 'EJS'],
    repository: 'https://github.com/devpilotX/value.codes',
    live: 'https://value.codes'
  },
  {
    name: 'TenderEdge',
    slug: 'tenderedge',
    domain: 'Procurement operations',
    summary: 'A multi-tenant tender and contract discovery system with matching, deadlines, documents, and live updates.',
    problem: 'Procurement teams need structured discovery and review across complex tender documents and deadlines.',
    systemDesign: 'Node.js and TypeScript application with PostgreSQL row-level security, partitioning, and WebSocket updates.',
    evidence: 'Repository signal: a public TypeScript B2B application with documented tenancy and data-layer architecture.',
    stack: ['TypeScript', 'Node.js', 'PostgreSQL', 'WebSockets'],
    repository: 'https://github.com/devpilotX/tenderedge',
    live: null
  },
  {
    name: 'Vouch Relay',
    slug: 'vouch-relay',
    domain: 'Identity confirmation',
    summary: 'A small Go relay for phone sign-in, device registration, pairing, and person-to-person verification.',
    problem: 'Voice and identity spoofing require a confirmation channel that does not depend on recognizing a fake.',
    systemDesign: 'Go standard-library HTTP service with swappable authentication, push, and storage interfaces plus PostgreSQL migration design.',
    evidence: 'Repository signal: documented endpoints, local zero-setup adapters, production Firebase and FCM paths, tests, vet, build, and CI.',
    stack: ['Go', 'PostgreSQL', 'Firebase', 'FCM'],
    repository: 'https://github.com/devpilotX/vouch-backend',
    live: null
  },
  {
    name: 'OU-MRS',
    slug: 'ou-mrs',
    domain: 'Quantitative systems research',
    summary: 'A Python research and paper-trading system for Ornstein-Uhlenbeck mean-reversion strategies.',
    problem: 'Systematic trading research needs reproducible signal logic, regime controls, risk limits, and validation before any live use.',
    systemDesign: 'Python modules for strategy logic, broker integration, backtesting, walk-forward analysis, Monte Carlo simulation, sizing, and operational controls.',
    evidence: 'Repository signal: dedicated validation tools, tests, telemetry, risk controls, and documented paper-first operating guidance.',
    stack: ['Python', 'FastAPI', 'Angel One SmartAPI'],
    repository: 'https://github.com/devpilotX/OU-MRS',
    live: null,
    disclaimer: 'Engineering and educational research only. It is not investment advice. Market losses can exceed deposits, and past results do not predict future returns.'
  },
  {
    name: 'Epicenter Exchange',
    slug: 'epicenter-exchange',
    domain: 'Financial education and research',
    summary: 'A free financial education platform with market views, calculators, research articles, and open-source signal demonstrations.',
    problem: 'Financial education is often mixed with promotions, paid signals, and unclear risk framing.',
    systemDesign: 'Static web frontend with a FastAPI and SQLite service, transactional email, calculators, dashboards, and consent-aware integrations.',
    evidence: 'Repository signal: public deployment, MIT license, legal pages, API documentation, deployment runbook, health checks, and educational disclaimers.',
    stack: ['HTML', 'JavaScript', 'Python', 'FastAPI', 'SQLite'],
    repository: 'https://github.com/devpilotX/epicenter-exchange',
    live: 'https://epicenterexchange.com',
    disclaimer: 'Educational content only. It is not investment advice. Consult a qualified adviser before making financial decisions.'
  },
  {
    name: 'Mergenote',
    slug: 'mergenote',
    domain: 'Engineering knowledge continuity',
    summary: 'A TypeScript project for preserving implementation context across code review and release workflows.',
    problem: 'Teams lose decision context when pull requests, review notes, and releases are separated.',
    systemDesign: 'Typed application flows that connect engineering notes with repository and release context.',
    evidence: 'Repository signal: a focused public TypeScript project for development workflow continuity.',
    stack: ['TypeScript'],
    repository: 'https://github.com/devpilotX/mergenote',
    live: null
  }
];

export const projectsBySlug = new Map(selectedProjects.map((project) => [project.slug, project]));
